In [3]:
#numpy-array manipulation
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr

array([[5, 6, 3, 4],
       [1, 7, 6, 8],
       [6, 9, 2, 7]])

In [6]:
#manipultating shape
arr.reshape(12,1)

array([[5],
       [6],
       [3],
       [4],
       [1],
       [7],
       [6],
       [8],
       [6],
       [9],
       [2],
       [7]])

In [7]:
arr.reshape(6,2)

array([[5, 6],
       [3, 4],
       [1, 7],
       [6, 8],
       [6, 9],
       [2, 7]])

In [8]:
arr

array([[5, 6, 3, 4],
       [1, 7, 6, 8],
       [6, 9, 2, 7]])

In [9]:
#transpose
arr.T

array([[5, 1, 6],
       [6, 7, 9],
       [3, 6, 2],
       [4, 8, 7]])

In [10]:
arr.flatten()

array([5, 6, 3, 4, 1, 7, 6, 8, 6, 9, 2, 7])

In [11]:
arr1=np.array([1,2,3,4])
arr1.ndim

1

In [12]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
#squeeze()

In [14]:
data= np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [15]:
np.squeeze(data)

array([1, 2, 3])

In [16]:
arr1

array([1, 2, 3, 4])

In [17]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [19]:
np.roll(arr1 ,shift=1) #array k element ko ghuma rha h

array([4, 1, 2, 3])

In [20]:
np.roll(arr1 ,shift=2)

array([3, 4, 1, 2])

In [21]:
np.roll(arr1 ,shift=3)


array([2, 3, 4, 1])

In [22]:
np.diag(arr1)  #put 1d data in diagonal 

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
#numpy - binary operations
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [26]:
arr1

array([[3, 8, 6, 5],
       [4, 9, 5, 1],
       [2, 5, 8, 4]])

In [27]:
arr2

array([[3, 8, 5, 6],
       [4, 3, 8, 6],
       [9, 5, 9, 8]])

In [28]:
arr1+arr2

array([[ 6, 16, 11, 11],
       [ 8, 12, 13,  7],
       [11, 10, 17, 12]])

In [29]:
arr1*arr2

array([[ 9, 64, 30, 30],
       [16, 27, 40,  6],
       [18, 25, 72, 32]])

In [31]:
arr1/arr2

array([[1.        , 1.        , 1.2       , 0.83333333],
       [1.        , 3.        , 0.625     , 0.16666667],
       [0.22222222, 1.        , 0.88888889, 0.5       ]])

In [32]:
arr1%arr2

array([[0, 0, 1, 5],
       [0, 0, 5, 1],
       [2, 0, 8, 4]])

In [33]:
arr1**arr2

array([[       27,  16777216,      7776,     15625],
       [      256,       729,    390625,         1],
       [      512,      3125, 134217728,     65536]])

In [34]:
~arr1

array([[ -4,  -9,  -7,  -6],
       [ -5, -10,  -6,  -2],
       [ -3,  -6,  -9,  -5]])

In [35]:
arr1|arr2

array([[ 3,  8,  7,  7],
       [ 4, 11, 13,  7],
       [11,  5,  9, 12]])

In [36]:
arr1>arr2

array([[False, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [37]:
#numpy string function
arr_str=np.array(['shikhar','saxena'])

In [38]:
np.char.upper(arr_str) #converting into uppercase

array(['SHIKHAR', 'SAXENA'], dtype='<U7')

In [39]:
np.char.title(arr_str)

array(['Shikhar', 'Saxena'], dtype='<U7')

In [40]:
np.char.capitalize(arr_str)

array(['Shikhar', 'Saxena'], dtype='<U7')

In [41]:
#numpy mathematical functions
arr1

array([[3, 8, 6, 5],
       [4, 9, 5, 1],
       [2, 5, 8, 4]])

In [42]:
np.sin(arr1)

array([[ 0.14112001,  0.98935825, -0.2794155 , -0.95892427],
       [-0.7568025 ,  0.41211849, -0.95892427,  0.84147098],
       [ 0.90929743, -0.95892427,  0.98935825, -0.7568025 ]])

In [43]:
np.cos(arr1)

array([[-0.9899925 , -0.14550003,  0.96017029,  0.28366219],
       [-0.65364362, -0.91113026,  0.28366219,  0.54030231],
       [-0.41614684,  0.28366219, -0.14550003, -0.65364362]])

In [44]:
np.tan(arr1)

array([[-0.14254654, -6.79971146, -0.29100619, -3.38051501],
       [ 1.15782128, -0.45231566, -3.38051501,  1.55740772],
       [-2.18503986, -3.38051501, -6.79971146,  1.15782128]])

In [45]:
np.tanh(arr1)

array([[0.99505475, 0.99999977, 0.99998771, 0.9999092 ],
       [0.9993293 , 0.99999997, 0.9999092 , 0.76159416],
       [0.96402758, 0.9999092 , 0.99999977, 0.9993293 ]])

In [46]:
np.log10(arr1)

array([[0.47712125, 0.90308999, 0.77815125, 0.69897   ],
       [0.60205999, 0.95424251, 0.69897   , 0.        ],
       [0.30103   , 0.69897   , 0.90308999, 0.60205999]])

In [47]:
np.exp(arr1)

array([[2.00855369e+01, 2.98095799e+03, 4.03428793e+02, 1.48413159e+02],
       [5.45981500e+01, 8.10308393e+03, 1.48413159e+02, 2.71828183e+00],
       [7.38905610e+00, 1.48413159e+02, 2.98095799e+03, 5.45981500e+01]])

In [48]:
np.sqrt(arr1)

array([[1.73205081, 2.82842712, 2.44948974, 2.23606798],
       [2.        , 3.        , 2.23606798, 1.        ],
       [1.41421356, 2.23606798, 2.82842712, 2.        ]])

In [49]:
np.power(arr1,2)

array([[ 9, 64, 36, 25],
       [16, 81, 25,  1],
       [ 4, 25, 64, 16]], dtype=int32)

In [50]:
np.mean(arr1)

5.0

In [51]:
np.median(arr1)

5.0

In [52]:
np.std(arr1)

2.345207879911715

In [53]:
np.var(arr1)

5.5

In [54]:
np.min(arr1)

1

In [55]:
np.max(arr1)

9