In [2]:
import numpy as np

In [3]:
l=[1,2,3,4,5]
ar=np.array(l)
type(ar)

numpy.ndarray

In [4]:
np.array([[1,2],[3,4]]) #2d array

array([[1, 2],
       [3, 4]])

In [5]:
#asarray() , asanyarray()also convert list into array
l1=[1,2,3,4,5,6]
np.asarray(l1)

array([1, 2, 3, 4, 5, 6])

In [6]:
l2=[1,2,3,4,5,6]
np.asanyarray(l2)

array([1, 2, 3, 4, 5, 6])

In [7]:
b=np.matrix(l) #matrix by default give 2d array 

In [8]:
b

matrix([[1, 2, 3, 4, 5]])

In [9]:
c=ar #c point array in same location as ar does
c   #swallow copy

array([1, 2, 3, 4, 5])

In [10]:
d=np.copy(ar) #copy at new location
d #deep copy

array([1, 2, 3, 4, 5])

In [11]:
np.fromfunction(lambda i,j : i==j,(3,3))  #this create 3x3 matrix where i==j 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [12]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [13]:
iter = (i*i for i in range(5))
np.fromiter(iter, float)

array([ 0.,  1.,  4.,  9., 16.])

In [14]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [15]:
#numpy datatypes
l=[2,3,4,5,6]
ar = np.array(l)
ar

array([2, 3, 4, 5, 6])

In [16]:
ar.ndim


1

In [17]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
ar2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
ar2.ndim

2

In [19]:
ar2.size

8

In [20]:
ar.shape

(5,)

In [32]:
ar2.shape

(2, 4)

In [21]:
ar.dtype

dtype('int32')

In [22]:
ar2.dtype

dtype('int32')

In [1]:
#we can't give floating point 
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
#but we can give it in numpy
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
np.zeros((3,4)) #(3,4) matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros((3,4,2)) #3 (4,2) matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [31]:
np.zeros((4,4,2)) #4 (4,2) matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
e=np.zeros((4,4,4,2)) #4 (4 (4,2) such matrix) such matrix
e

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
 

In [33]:
e.ndim

4

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
on=np.ones((3,4,4))
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [37]:
np.ones((2,3,4,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [40]:
on+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [44]:
np.empty((3,3))

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [45]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.logspace(2,5,  10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [47]:
np.logspace(2,5,  10 , base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [51]:
arr=np.random.randn(3,4) #generate random data
arr

array([[ 0.28329482, -0.6769461 , -1.19687786, -1.0195813 ],
       [-0.15304622,  0.36466905, -0.53903236, -1.5730178 ],
       [-0.73978846,  0.31766005,  0.87192521,  0.75898771]])

In [49]:
import pandas as pd

In [52]:
pd.DataFrame(arr)

0         1         2         3
0  0.283295 -0.676946 -1.196878 -1.019581
1 -0.153046  0.364669 -0.539032 -1.573018
2 -0.739788  0.317660  0.871925  0.758988

In [57]:
arrr=np.random.randint(1,510,(3,4))
arrr

array([[ 69, 168, 138,  32],
       [ 37, 100, 232,  17],
       [416, 445, 477, 115]])

In [58]:
arrre=np.random.rand(3,4) #total 12 elements are there 
arrre

array([[0.83679783, 0.39868418, 0.9928284 , 0.81178973],
       [0.73569941, 0.89849038, 0.30757134, 0.91144384],
       [0.38897323, 0.92176775, 0.45160824, 0.75057811]])

In [59]:
arrre.reshape(6,2) #usign reshape we can change above data in (6,2) matrix or any other matrix which contain 12 elements

array([[0.83679783, 0.39868418],
       [0.9928284 , 0.81178973],
       [0.73569941, 0.89849038],
       [0.30757134, 0.91144384],
       [0.38897323, 0.92176775],
       [0.45160824, 0.75057811]])

In [61]:
#indexing
arrre

array([[0.83679783, 0.39868418, 0.9928284 , 0.81178973],
       [0.73569941, 0.89849038, 0.30757134, 0.91144384],
       [0.38897323, 0.92176775, 0.45160824, 0.75057811]])

In [62]:
arrre[1][1]

0.8984903798373789

In [76]:
arrre[2][0:3]

array([0.38897323, 0.92176775, 0.45160824])

In [77]:
# ----------------------------------
ar=np.random.randint(1,100,(5,5))
ar

array([[35, 97, 51, 16, 26],
       [74, 90, 36, 90, 88],
       [50, 69,  4, 25, 30],
       [38, 60, 81, 27, 82],
       [39, 34, 75, 43, 40]])

In [81]:
#finding data which is greater then 50
ar[ar>50]

array([97, 51, 74, 90, 90, 88, 69, 60, 81, 82, 75])

In [82]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))
arr1+arr2

array([[2, 3, 3],
       [2, 4, 2],
       [2, 2, 3]])

In [83]:
arr1/arr2

array([[1. , 2. , 0.5],
       [1. , 1. , 1. ],
       [1. , 1. , 2. ]])

In [84]:
arr1*arr2 #simple index multiplication

array([[1, 2, 2],
       [1, 4, 1],
       [1, 1, 2]])

In [85]:
#matrix multiplication
arr1@arr2

array([[4, 6, 5],
       [4, 6, 5],
       [4, 5, 5]])

In [88]:
#numpy - broadcasting
arr3=np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [89]:
#rotating array , #transpose always rotate 2d array , if we give 1d then it will not roatate
arr3.T

array([1, 2, 3, 4])

In [90]:
#givind 2d array
arr3=np.array([[1,2,3,4]])
arr3
arr3.T

array([[1],
       [2],
       [3],
       [4]])

In [91]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081, 2.        ]])