In [1]:
#sort , search and counting functions
import numpy as np

In [2]:
arr=np.array([2,3,4,1,4,3,2,455,5,6,67,72])

In [3]:
arr

array([  2,   3,   4,   1,   4,   3,   2, 455,   5,   6,  67,  72])

In [4]:
np.sort(arr)

array([  1,   2,   2,   3,   3,   4,   4,   5,   6,  67,  72, 455])

In [5]:
np.searchsorted(arr,34) # it tells where the 34 will locate in sorted array arr

10

In [6]:
arr1=np.array([0,3,4,0,0,0,0,0,1,0,0,0,0,0,])
np.count_nonzero(arr1)

3

In [8]:
arr

array([  2,   3,   4,   1,   4,   3,   2, 455,   5,   6,  67,  72])

In [7]:
np.where(arr>6)

(array([ 7, 10, 11], dtype=int64),)

In [10]:
np.extract(arr>6,arr)

array([455,  67,  72])

In [11]:
#numpy byte swaping
arr.byteswap()

array([  33554432,   50331648,   67108864,   16777216,   67108864,
         50331648,   33554432, -956235776,   83886080,  100663296,
       1124073472, 1207959552])

In [12]:
#numpy copies and views
arr

array([  2,   3,   4,   1,   4,   3,   2, 455,   5,   6,  67,  72])

In [13]:
a=np.copy(arr) #deep copy

In [14]:
a

array([  2,   3,   4,   1,   4,   3,   2, 455,   5,   6,  67,  72])

In [15]:
b=arr.view() #swallow copy

In [16]:
b

array([  2,   3,   4,   1,   4,   3,   2, 455,   5,   6,  67,  72])

In [17]:
#numpy matrix liberary
import numpy.matlib as nm

In [18]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [19]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
#numpy linear algebra

In [22]:
arr1=np.random.randint([[2,3],[4,5]])

In [24]:
arr2=np.random.randint([[2,3],[4,5]])

In [25]:
np.dot(arr1,arr2)

array([[0, 0],
       [4, 0]])

In [26]:
arr1@arr2

array([[0, 0],
       [4, 0]])